### ISSUE TITLE
An error occurred while using the program.

### ISSUE THREAD

**Issue by dfdfdfs** [sc2ad/Il2Cpp-Modding-Codegen#12]
Drag and drop your dump.cs file (or a partial of it of the correct format) then press enter...
dump.cs
Parsing...
Unhandled exception. System.InvalidOperationException: Line 442: Method cannot be created from: ""
   at Il2CppModdingCodegen.Data.DumpHandling.DumpMethod..ctor(TypeRef declaring, PeekableStreamReader fs) in D:\games\Il2Cpp-Modding-Codegen\Il2Cpp-Modding-Codegen\Data\DumpHandling\DumpMethod.cs:line 47
   at Il2CppModdingCodegen.Data.DumpHandling.DumpTypeData.ParseMethods(PeekableStreamReader fs) in D:\games\Il2Cpp-Modding-Codegen\Il2Cpp-Modding-Codegen\Data\DumpHandling\DumpTypeData.cs:line 184
   at Il2CppModdingCodegen.Data.DumpHandling.DumpTypeData..ctor(PeekableStreamReader fs, DumpConfig config) in D:\games\Il2Cpp-Modding-Codegen\Il2Cpp-Modding-Codegen\Data\DumpHandling\DumpTypeData.cs:line 220
   at Il2CppModdingCodegen.Data.DumpHandling.DumpData.ParseTypes(PeekableStreamReader fs) in D:\games\Il2Cpp-Modding-Codegen\Il2Cpp-Modding-Codegen\Data\DumpHandling\DumpData.cs:line 43
   at Il2CppModdingCodegen.Data.DumpHandling.DumpData.Parse(PeekableStreamReader fs) in D:\games\Il2Cpp-Modding-Codegen\Il2Cpp-Modding-Codegen\Data\DumpHandling\DumpData.cs:line 61
   at Il2CppModdingCodegen.Data.DumpHandling.DumpData..ctor(Stream stream, DumpConfig config) in D:\games\Il2Cpp-Modding-Codegen\Il2Cpp-Modding-Codegen\Data\DumpHandling\DumpData.cs:line 74
   at Il2CppModdingCodegen.DumpParser.Parse(Stream stream) in D:\games\Il2Cpp-Modding-Codegen\Il2Cpp-Modding-Codegen\Parsers\DumpParser.cs:line 17
   at Codegen_CLI.Program.Main(String[] args) in D:\games\Il2Cpp-Modding-Codegen\Codegen-CLI\Program.cs:line 46
![90мок](https://user-images.githubusercontent.com/24856424/103130494-f645fb00-46ad-11eb-8427-51fcb3632718.PNG)

**Comment by sc2ad** [comment]
Apologies for not seeing this sooner, but please use the dummy dll mode for now. Feel free to reopen this issue if you still have issues, I would be happy to work them out!

**Comment by ATXLtheAxolotl** [comment]
> Apologies for not seeing this sooner, but please use the dummy dll mode for now. Feel free to reopen this issue if you still have issues, I would be happy to work them out!

I'm having the same problems, how would I enable dummy dll mode?

**Comment by ATXLtheAxolotl** [comment]
> > Apologies for not seeing this sooner, but please use the dummy dll mode for now. Feel free to reopen this issue if you still have issues, I would be happy to work them out!
> 
> I'm having the same problems, how would I enable dummy dll mode?

Anyone having the same problem the fix is just to give the path of the dlls.
